version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: Install frontend dependencies
          command: npm run frontend_install
      - run:
          name: build frontend
          command: npm run frontend_build
      #- run:
      #    name: test frontend
      #    command: npm run frontend_test
      - run:
          name: deploy frontend
          command: npm run frontend_deploy
      - run:
          name: Install backend dependencies
          command: npm run api_install
      - run:
          name: build backend
          command: npm run api_build
      #- run:
      #    name: test backend
      #    command: npm run api_test
      - run:
          name: deploy backend
          command: npm run api_deploy
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
